# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10IvOIo7Ifb-F02x8OSOkUsv1xNJZH9bW
"""

from flask import Flask, render_template, request
import numpy as np
import pickle

app = Flask(__name__)
filename = 'RFC_model.pkl'
model = pickle.load(open(filename, 'rb'))

@app.route('/')
def index():
  return render_template('index.html')

@app.route('/predict', methods=['POST'])
def predict():
        fixed_acidity = request.form.get('fixed_acidity')
        volatile_acidity = request.form.get('volatile_acidity')
        citric_acid = request.form.get('citric_acid')
        residual_sugar = request.form.get('residual_sugar')
        chlorides = request.form.get('chlorides')
        free_sulfur_dioxide = request.form.get('free_sulfur_dioxide')
        total_sulfur_dioxide = request.form.get('total_sulfur_dioxide')
        density = request.form.get('density')
        pH = request.form.get('pH')
        sulphates = request.form.get('sulphates')
        alcohol = request.form.get('alcohol')
        features = [
            float(fixed_acidity),
            float(volatile_acidity),
            float(citric_acid),
            float(residual_sugar),
            float(chlorides),
            float(free_sulfur_dioxide),
            float(total_sulfur_dioxide),
            float(density),
            float(pH),
            float (sulphates),
            float(alcohol)]
        prediction = model.predict([features])[0]
        return render_template('index.html', prediction=prediction)

if __name__ == '__main__':
    app.run(debug=True)